POST https://medtracker-api-jtan.onrender.com/remedios
Content-type: application/json

{
    "name": "Remedio",
    "dosage": "30mg",
    "totalPills": 13,
    "frequencyHours": 6,
    "startDate": "2022-03-01",
    "endDate": "2022-03-10"
}

###

GET https://medtracker-api-jtan.onrender.com/remedios


###

PUT https://medtracker-api-jtan.onrender.com/remedios/4
Content-type: application/json

{
    "name": "Remedio2",
    "dosage": "20mg",
    "totalPills": 20,
    "frequencyHours": 22,
    "startDate": "2022-02-01",
    "endDate": "2022-02-10"
}

###

DELETE https://medtracker-api-jtan.onrender.com/remedios/4